# Configure default config
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: []
script: []
scene: []

# Example configuration.yaml entry
light:
  - platform: group
    name: Living Room
    entities:
      - light.living_room_main
      - light.living_room_lamp

# Example sensor
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

# Example switch
switch:
  - platform: template
    switches:
      example_switch:
        friendly_name: "Example Switch"
        value_template: "{{ states('input_boolean.example_switch') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.example_switch
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.example_switch

# Required for the example switch
input_boolean:
  example_switch:
    name: Example Switch State